# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Ninety-Nine Capstone
email: skylera@duck.com
tagline: "CSUCI Capstone Project"
description: 'A Pygame implementation of the card game Ninety-Nine. Created by <a href=GitHub.com/SkylerMime target="_blank">Skyler Atchison</a>'
domain: skylermime.github.io
url: https://skylermime.github.io
baseurl: /NinetyNine
github_username: SkylerMime

# Custom vars
version: 2.1.0
pagination: 5
